name: Daily Ad Data to Supabase

# ① 언제 실행할지 설정
on:
  schedule:
    # 서울시간 아침 8시(UTC 23:00)에 실행
    - cron: '0 23 * * *'
  # 수동 실행도 가능하게 워크플로우 디스패치 허용
  workflow_dispatch: 

jobs:
  fetch-and-upsert:
    name: Fetch All Platforms & Upsert to Supabase
    runs-on: ubuntu-latest

    steps:
      # 1) 리포지토리 체크아웃
      - uses: actions/checkout@v3

      # 2) Node.js 환경 세팅
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # 필요 시 버전 조정

      # 3) 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4) 모든 플랫폼 데이터 수집 (통합)
      - name: Fetch All Platforms & upsert to Supabase
        env:
          # Meta 환경변수
          META_TOKEN: ${{ secrets.META_TOKEN }}
          AD_ACCOUNT: ${{ secrets.AD_ACCOUNT }}
          # Google 환경변수
          GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GOOGLE_DEVELOPER_TOKEN: ${{ secrets.GOOGLE_DEVELOPER_TOKEN }}
          GOOGLE_CUSTOMER_ID: ${{ secrets.GOOGLE_CUSTOMER_ID }}
          GOOGLE_CLIENT_CUSTOMER_ID: ${{ secrets.GOOGLE_CLIENT_CUSTOMER_ID }}
          # Naver 환경변수
          NAVER_API_KEY: ${{ secrets.NAVER_API_KEY }}
          NAVER_SECRET_KEY: ${{ secrets.NAVER_SECRET_KEY }}
          NAVER_CUSTOMER_ID: ${{ secrets.NAVER_CUSTOMER_ID }}
          # Supabase 환경변수
          SUPA_URL: ${{ secrets.SUPA_URL }}
          SUPA_KEY: ${{ secrets.SUPA_KEY }}
        run: node scripts/fetch-all-platforms.js
