name: Daily Ad Data to Supabase

# ① 언제 실행할지 설정
on:
  schedule:
    # 서울시간 아침 7시(UTC 22:00)에 실행
    - cron: '0 22 * * *'
  # 수동 실행도 가능하게 워크플로우 디스패치 허용
  workflow_dispatch: 

jobs:
  fetch-and-upsert:
    name: Fetch All Platforms & Upsert to Supabase
    runs-on: ubuntu-latest

    steps:
      # 1) 리포지토리 체크아웃
      - uses: actions/checkout@v3

      # 2) Node.js 환경 세팅
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # 필요 시 버전 조정

      # 3) 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4) 모든 플랫폼 데이터 수집 (통합)
      - name: Fetch All Platforms & upsert to Supabase
        env:
          # 기존 브랜드 - Meta 환경변수
          META_TOKEN: ${{ secrets.META_TOKEN }}
          META_AD_ACCOUNT: ${{ secrets.META_AD_ACCOUNT }}
          # 기존 브랜드 - Google 환경변수
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GOOGLE_DEVELOPER_TOKEN: ${{ secrets.GOOGLE_DEVELOPER_TOKEN }}
          GOOGLE_CUSTOMER_ID: ${{ secrets.GOOGLE_CUSTOMER_ID }}
          GOOGLE_CLIENT_CUSTOMER_ID: ${{ secrets.GOOGLE_CLIENT_CUSTOMER_ID }}
          # 기존 브랜드 - Naver 환경변수
          NAVER_API_KEY: ${{ secrets.NAVER_API_KEY }}
          NAVER_SECRET_KEY: ${{ secrets.NAVER_SECRET_KEY }}
          NAVER_CUSTOMER_ID: ${{ secrets.NAVER_CUSTOMER_ID }}
          # DOK 브랜드 - Meta 환경변수
          DOK_META_TOKEN: ${{ secrets.DOK_META_TOKEN }}
          DOK_META_AD_ACCOUNT: ${{ secrets.DOK_META_AD_ACCOUNT }}
          # DOK 브랜드 - Google 환경변수
          DOK_GOOGLE_CUSTOMER_ID: ${{ secrets.DOK_GOOGLE_CUSTOMER_ID }}
          DOK_GOOGLE_CLIENT_CUSTOMER_ID: ${{ secrets.DOK_GOOGLE_CLIENT_CUSTOMER_ID }}
          # DOK 브랜드 - Naver 환경변수
          DOK_NAVER_API_KEY: ${{ secrets.DOK_NAVER_API_KEY }}
          DOK_NAVER_SECRET_KEY: ${{ secrets.DOK_NAVER_SECRET_KEY }}
          DOK_NAVER_CUSTOMER_ID: ${{ secrets.DOK_NAVER_CUSTOMER_ID }}
          # Supabase 환경변수 (공통)
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node scripts/fetch-all-platforms.js
