name: Daily Ad Data to Supabase

# ① 언제 실행할지 설정
on:
  schedule:
    # 서울시간 아침 9시(UTC 자정 00:00)에 실행
    - cron: '0 0 * * *'
  # 수동 실행도 가능하게 워크플로우 디스패치 허용
  workflow_dispatch: 

jobs:
  fetch-and-upsert:
    name: Fetch All Platforms & Upsert to Supabase
    runs-on: ubuntu-latest

    steps:
      # 1) 리포지토리 체크아웃
      - uses: actions/checkout@v3

      # 2) Node.js 환경 세팅
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # 필요 시 버전 조정

      # 3) 의존성 설치
      - name: Install dependencies
        run: npm ci

      # 4) Meta 데이터 수집
      - name: Fetch Meta & upsert to Supabase
        continue-on-error: true  # Meta 실패해도 계속 진행
        env:
          META_TOKEN: ${{ secrets.META_TOKEN }}
          AD_ACCOUNT: ${{ secrets.AD_ACCOUNT }}
          SUPA_URL:   ${{ secrets.SUPA_URL }}
          SUPA_KEY:   ${{ secrets.SUPA_KEY }}
        run: node scripts/fetch-meta.js

      # 5) Naver 데이터 수집
      - name: Fetch Naver & upsert to Supabase
        continue-on-error: true  # Naver 실패해도 워크플로우는 성공으로 표시
        env:
          NAVER_API_KEY: ${{ secrets.NAVER_API_KEY }}
          NAVER_SECRET_KEY: ${{ secrets.NAVER_SECRET_KEY }}
          NAVER_CUSTOMER_ID: ${{ secrets.NAVER_CUSTOMER_ID }}
          SUPA_URL: ${{ secrets.SUPA_URL }}
          SUPA_KEY: ${{ secrets.SUPA_KEY }}
        run: node scripts/fetch-naver.js
